apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.serviceAccount.name }}
  labels: 
    app: image-processing
spec:
  selector:
    app: image-processing
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 3000
      protocol: TCP
      
